### ISSUE TITLE
Input clone ?

### ISSUE THREAD

**Issue by Farkal** [davidpdrsn/juniper-from-schema#110]
How do you manage to clone a GraphQL input ?
For example I have one input and i need to create two objects from it (I have implemented from but it move the object). 
The Clone is not implemented on the input object. Is there any easy way to do that ? (Using the directive ?)

**Comment by davidpdrsn** [comment]
Yeah you're right. `Clone` is not derived for input types. I simply forgot and haven't run into it yet. 

You're welcome to submit a PR if you're up for it. Should only require a change [here](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema-code-gen/src/ast_pass/code_gen_pass.rs#L494) and a new test [here](https://github.com/davidpdrsn/juniper-from-schema/tree/master/juniper-from-schema/tests/compile_pass) that calls `.clone` on some input object.

Until then, since the definition of the input object struct is inserted into your code, you can actually implement `Clone` yourself. You cannot quite derive it yet however.
