### ISSUE TITLE
Allow customizing Context name

### ISSUE THREAD

**Issue by david0u0** [davidpdrsn/juniper-from-schema#59]
Hi, I'm using the crate to generate my api codes, and most of it works excellent. However, I find it helpful if the crate allows customizing the name of context struct.

According to the document, this will work:
```rust
graphql_schema_from_file!("tests/schemas/doc_schema.graphql");

pub struct Context;
impl juniper::Context for Context {}

pub struct Query;

impl QueryFields for Query {
    fn field_hello_world(
        &self,
        executor: &juniper::Executor<'_, Context>,
        name: String,
    ) -> juniper::FieldResult<String> {
        Ok(format!("Hello, {}!", name))
    }
}
```
But it won't work if I change the `Context` to some other name:
```rust
pub struct MyContext;
impl juniper::Context for MyContext {}
```
```sh
error[E0412]: cannot find type `Context` in this scope
 --> src/main.rs:5:1
  |
5 | graphql_schema_from_file!("./src/api.gql");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I think it will be nice to simply add another parse option `context_type` such that I can write
```rust
graphql_schema_from_file!("tests/schemas/doc_schema.graphql", context_type: MyContext);
```

Thanks!

**Comment by davidpdrsn** [comment]
I think thats a totally reasonable feature that we should support. I have also thought about it myself but since I didn't need it I haven't built it.

Is this something you would be willing to implement and submit in a PR? I imagine most of changes would be in the [code that parses the input](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema-code-gen/src/parse_input.rs) and in the [code that generates the final juniper code](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema-code-gen/src/ast_pass/code_gen_pass.rs). You're welcome to submit a draft PR for me to leave feedback on or finish implementing if you get stuck.
